pipeline:      
  jekyll-build:
    image: jekyll/jekyll:latest
    commands:
      - touch Gemfile.lock
      - chmod a+w Gemfile.lock
      - chown -R jekyll:jekyll /drone
      - gem update --system
      - gem install bundler
      - bundle install
      - bundle exec jekyll build 

  transfer-build:
    image: drillster/drone-rsync
    hosts: 
      from_secret: swarm_host
    key:
      from_secret: swarm_key
    user:
      from_secret: swarm_user
    script:
      - find .
      - mkdir -p ~/serverless-tutorials.com/_site
    source: ./*
    target: ~/serverless-tutorials.com
    recursive: true
    delete: true
    when:
      branch: [master]
      event: [push]
      
  transfer-compose:
    image: appleboy/drone-scp
    host: 
      from_secret: swarm_host
    username:
      from_secret: swarm_user
    key:
      from_secret: swarm_key
    target: /root/serverless-tutorials.com
    source:
      - docker-compose.yml
    when:
      branch: [master]
      event: [push]
     
  deploy-jekyll-to-swarm:
    image: appleboy/drone-ssh
    host: 
      from_secret: swarm_host
    username:
      from_secret: swarm_user
    key:
      from_secret: swarm_key
    port: 22
    script:
      - docker stack deploy --prune -c /root/serverless-tutorials.com/docker-compose.yml apps
    when:
      branch: [master]
      event: [push]
